### ISSUE TITLE
fj ligature demo in selnolig-german-test.tex

### ISSUE THREAD

**Issue by doncherry** [micoloretan/selnolig#6]
Line 49 currently ends with:

``` latex
& fj &\mbox{fk}\\
```

That should be:

``` latex
& \mbox{fj} &\mbox{fk}\\
```

(See the pdf)

**Comment by koppor** [comment]
I don't find this line any more. Is it that one? https://github.com/micoloretan/selnolig/blob/674f06ce7f35e8719b20593b8d70f90a458836a9/selnolig-german-test.tex#L52

**Comment by micoloretan** [comment]
Hi! If I recall correctly [!], much of the low-level code of the selnolig package was still undergoing considerable change in early 2013 -- that's when Felix/"doncherry" posted the note you came across. In particular, I recall that \mbox was for a long time a rather unreliable way of "shielding" words from selnolig's prying eyes. Eventually, we changed the code so that \mbox was no longer a shield at all. selnolig disables 'fj' and 'fk' ligatures globally, assuming that either 'german' or 'english' is in effect. For the two-row table in question, the ligatures had to be re-enabled explicitly. That's where the \uselig macro comes in handy. :-)

**Comment by koppor** [comment]
Sure! Then it's time to close this issue. 😇
